name: hello_world

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "what is up today"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: goodbye-world
        run: echo "goodbye to all the world"
        shell: bash